### ISSUE TITLE
Friend Finder Panel 7.0

### ISSUE THREAD

**Issue by jshen340** [jshen340/uniBuzzy-GaTech-Team#10]
### Task Description
 -Complete the framework for Panel 7.0's layout
- https://www.figma.com/file/q5msvGoANGkapiq8F8LCeo/uniBuzzy-Friend-Finder?type=design&node-id=201-416&mode=design&t=PjesHdjtUOjcpM2w-0
### Dependencies
- None
### Done
- [ ] Formatted text
- [ ] Interactive stars that respond when users select them, filling in all others on the left
- [ ] Functional text box that takes in user input
- [ ] Go back (home screen) button
- [ ] Submit button
### Execution Plan
- [ ]  Steps to complete
