### ISSUE TITLE
Friend Finder Panel 6.75

### ISSUE THREAD

**Issue by jshen340** [jshen340/uniBuzzy-GaTech-Team#12]
### Task Description
 - Complete the framework for Panel 6.75's layout
- https://www.figma.com/file/q5msvGoANGkapiq8F8LCeo/uniBuzzy-Friend-Finder?type=design&node-id=201-416&mode=design&t=PjesHdjtUOjcpM2w-0
### Dependencies
- None
### Done
- [ ] Formatted text
- [ ] Dropdown menu (15, 30, 45 minutes options)
- [ ] Stop waiting button
### Execution Plan
- [ ]  Steps to complete
